### ISSUE TITLE
php's split() is deprecated

### ISSUE THREAD

**Issue by benlk** [npr/nprapi-wordpress#31]
```
PHP Deprecated:  Function split() is deprecated in /vagrant/wp-content/plugins/WP-DS-NPR-API/classes/NPRAPIWordpress.php on line 59
```

https://secure.php.net/manual/en/function.split.php

It looks like this is being used as `explode()`, even though it's the anlogue to `preg_split()`

**Comment by mikeschinkel** [comment]
See PR 32 that addresses this and several other issues:

- https://github.com/nprds/nprapi-wordpress/pull/32

**Comment by benlk** [comment]
https://github.com/npr/nprapi-wordpress/pull/42 addresses the remaining join/split.
