### ISSUE TITLE
Post box does not appear if settings are not saved

### ISSUE THREAD

**Issue by benlk** [npr/nprapi-wordpress#51]
From one or our stations we are hearing:

> Just updated to the Wordpress API plugin version that was just released and I do not have a box anywhere for NPROne. I have looked in the documentation and that box is not available on my screen or options. What happened?

Then from the same station:

> Also noted. I have never had the API PUSH URL plugged in with the old version of the API plugin (﻿﻿http://api.npr.org). I found that if I set the Push URL and save that the NPROne box will appear in the story editor screen

- [ ] improve docs regarding this
- [ ] prompt in admin for manage_plugins users to save these settings, if not they are not saved.

**Comment by kaylima** [comment]
**Acceptance criteria**

- [ ] Plugin messages user if they try to engage with it unconfigured. 
- [ ] Documentation/messaging in UI reviewed and accepted by Erin Teare and Janeen Williamson.
