### ISSUE TITLE
When site has no GMT offset saved, the expiry datetime causes problems

### ISSUE THREAD

**Issue by benlk** [npr/nprapi-wordpress#52]
When the `'gmt_offset'` value is a number (which is pretty much everywhen), the DateTimeZone constructor complains that the number is not a valid timezone. 

https://github.com/npr/nprapi-wordpress/blob/853a3011aafa9727a8742111305ff3194abca236/push_story.php#L676-L679

> PHP Fatal Error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (-4)' in /plugins/npr-story-api/psuh_story.php:676'

- [ ] make plugin draw from `'timezone_string'` when `'gmt_offset'` is unset, in [ function `nprstory_get_post_expiry_datetime()`](https://github.com/npr/nprapi-wordpress/blob/853a3011aafa9727a8742111305ff3194abca236/push_story.php#L668) and in [function `nprstory_save_datetime()`](https://github.com/npr/nprapi-wordpress/blob/853a3011aafa9727a8742111305ff3194abca236/push_story.php#L644)
- [ ] provide fallback behavior for when those meta are not set
- [ ] add test case that runs `nprstory_get_post_expiry_datetime( $post )` with every valid GMT offset and with every time zone and with nothing set for either. 
    - [ ] when running against every time zone, the list at https://secure.php.net/manual/en/datetimezone.listabbreviations.php will need to be wp_list_pluck'd to get the timezone_id value, and then will need to be sort/uniq'd.

**Comment by benlk** [comment]
Timezones are not a specific GMT offset; we need a GMT offset for this. A better approach is described in https://github.com/npr/nprapi-wordpress/pull/53.

**Comment by kaylima** [comment]
TODO: Up to 2 hours for remaining testing for #53 .

**Comment by benlk** [comment]
Automated tests for #53 pass.

Human-run tests for #53 should perform the following tasks:

1. Activate the plugin
2. Configure the plugin with test API credentials
3. Create a new post.
    1. Does the NPR Story API meta box appear on the page?
    2. Are there no errors in the server console?
    3. Change the time zone in Dashboard > Settings > General to a new time zone. Repeat step 3 until satisfied. 
4. Push a post to the API.
5. Pull a post from the API.
