### ISSUE TITLE
Release Updates

### ISSUE THREAD

**Issue by kaylima** [npr/nprapi-wordpress#55]
After fixes for issues #51 and/or #52 are merged:

- [x] update the version number to 1.8
- [x] check that contributors are properly attributed
- [x] update changelog in readme.txt and elsewhere
- [x] fix header formatting in README.md
- [x] deploy an update to the plugin to WordPress.org

**Comment by benlk** [comment]
Draft release is at https://github.com/npr/nprapi-wordpress/releases/tag/untagged-3a1d3554f4c573173599, will be https://github.com/npr/nprapi-wordpress/releases/tag/1.8 when published.

Pull request to implement the version number bump is https://github.com/npr/nprapi-wordpress/pull/58
