### ISSUE TITLE
Problems pushing content to the API

### ISSUE THREAD

**Issue by benlk** [npr/nprapi-wordpress#57]
Reported by @eteare:

>  I have been struggling to publish to the Story API from the plugin. I can get stories from the Story API no prob (one story, or an auto publish of a collection), but no PUT or POST from the site I am testing on. We are looking at Kibana to find these requests.
> 
> I’ve gone round a few times, checking all the configs and Ben, can you double check one thing for us? Can you check that for POST and PUT requests that the URL is `/story` and not `/query`? That’s the one guess we have right now on why, perhaps, no stories are getting to the API.

**Comment by benlk** [comment]
When pushing content to the API, the URL is /story and it is making a POST request: https://github.com/npr/nprapi-wordpress/blob/26a44bf00efd1c43b2f9346888fe7a2f7ccb51f1/classes/NPRAPIWordpress.php#L547-L554

Erin says that NPR is taking another look to see if they can determine what the problem is.

**Comment by benlk** [comment]
I'm not even seeing the "org ID not set" error that should be showing in my server log, because I'm attempting to push to the sandbox without an Org ID.

https://github.com/npr/nprapi-wordpress/blob/26a44bf00efd1c43b2f9346888fe7a2f7ccb51f1/classes/NPRAPIWordpress.php#L582-L585

**Comment by benlk** [comment]
It's because this URL parameter is no longer set:

https://github.com/npr/nprapi-wordpress/blob/a58353bdbe3bb30acb89751094e3b8cb5fd7ba1a/push_story.php#L124-L128

That URL parameter was set before https://github.com/npr/nprapi-wordpress/pull/47, and is not set afterwards. The pull request removed the `submit_button( 'Push to NPR', 'large', 'ds_npr_update_push', false, $attrs );` button, which set that URL parameter, and replaced it with a checkbox that added a different parameter to the URL.

**Comment by benlk** [comment]
With an org ID set:

> Fatal error: Uncaught Error: Cannot use string offset as an array in /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/push_story.php:463
> Stack trace:
> 0 /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/settings.php(238): nprstory_get_permission_groups()
> 1 /Users/blk/sites/nprapi/wp-admin/includes/template.php(1388): nprstory_push_story_permissions_callback(Array)
> 2 /Users/blk/sites/nprapi/wp-admin/includes/template.php(1347): do_settings_fields('ds_npr_api', 'ds_npr_api_sett...')
> 3 /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/settings_ui.php(14): do_settings_sections('ds_npr_api')
> 4 /Users/blk/sites/nprapi/wp-includes/class-wp-hook.php(286): nprstory_api_options_page('')
> 5 /Users/blk/sites/nprapi/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
> 6 /Users/blk/sites/nprapi/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> 7 /Users/blk/sites/nprapi/wp-admin/admin.php(224): do_action('settings_page_d...')
> 8 /Users/blk/sites/nprapi/wp-admin/options-general.php(10): require_once('/Users/blk/site...')
> 9 /Users/blk/.composer/vendor/laravel/valet/server.php(147): require('/Users/blk/site...')
> 10 {main}
> 
> thrown in /Users/blk/sites/nprapi/wp-content/plugins/nprapi-wordpress/push_story.php on line 463
>

**Comment by benlk** [comment]
That's fixed by https://github.com/npr/nprapi-wordpress/pull/60/commits/63c25f0f5b6c4ec2d1da436bd202be803c885461

**Comment by eteare** [comment]
Ben, I pulled a repo with this branch and successfully posted to the API. Success!

**Comment by benlk** [comment]
👍

**Comment by benlk** [comment]
#60 has merged, so moving this to the "Done" category.
